# Generated by Django 5.0.4 on 2024-04-28 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MorshedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True)),
                ('student_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('student_address', models.TextField(blank=True, null=True)),
                ('student_age', models.IntegerField(blank=True, null=True)),
                ('morshed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morshed_student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_process', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
