# Generated by Django 4.2.10 on 2024-04-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='morshedstudent',
            old_name='student_name',
            new_name='student_major',
        ),
        migrations.RemoveField(
            model_name='morshedstudent',
            name='student_age',
        ),
        migrations.RemoveField(
            model_name='morshedstudent',
            name='student_email',
        ),
        migrations.AddField(
            model_name='morshedstudent',
            name='student_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
