version: "3.9"

services:

  # database container for task management service
  db_tms:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db_tms
    ports:
      - "3307:3306"
    expose:
      - 3307
    volumes:
      - tms_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root_123'
      MYSQL_DATABASE_NAME: 'tmsdb'
      MYSQL_ROOT_HOST: 'localhost'
      MYSQL_PORT: '3306'
    networks:
      TMS-network:
        aliases:
          - db_tms

  # database container for users management service
  db_ums:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: db_ums
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ums_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'umsdb'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root_123'
      MYSQL_PASSWORD: 'user123'
    networks:
      TMS-network:
        aliases:
          - db_ums

  # task management service container
  backend-tms:
    image: python-service:latest
    build:
      dockerfile: backend/python_services/Dockerfile
    container_name: TMS-backend-tms
    volumes:
      - ./backend/python_services/task_management_service/:/app/backend/task_management_service
      - ./backend/python_services/:/app/backend
    ports:
      - "3000:3000"
    command: "uvicorn task_management_service.main:app --host 0.0.0.0 --port 3000 --reload"
    depends_on:
      db_tms:
        condition: service_started
    networks:
      TMS-network:
        aliases:
          - tms-network

  # users management service container
  backend-ums:
    image: python-service:latest
    build:
      dockerfile: backend/python_services/Dockerfile
    container_name: TMS-backend-ums
    volumes:
      - ./backend/python_services/users_management_service/:/app/backend/users_management_service
      - ./backend/python_services/:/app/backend
    ports:
      - "8000:8000"
    command: "python ./users_management_service/manage.py runserver  0.0.0.0:8000"
    depends_on:
      db_ums:
        condition: service_started
    networks:
      TMS-network:
        aliases:
          - ums-network

  # node js container
  backend-nodejs:
    image: node:latest
    build:
      dockerfile: backend/node_services/Dockerfile
    container_name: TMS-backend-nodejs
    volumes:
      - ./backend/node_services/:/app/node_services
    ports:
      - "4000:4000"
    command: "npm start 0.0.0.0:4000"
    networks:
      TMS-network:
        aliases:
          - backend-nodejs

  # react app container
  frontend:
    image: frontend:latest
    build:
      dockerfile: frontend/Dockerfile
    container_name: TMS-frontend
    volumes:
      - ./frontend/app:/app
    ports:
      - "9000:9000"
    command: "npm start 0.0.0.0:9000"
    depends_on:
      backend-tms:
        condition: service_started
      backend-ums:
        condition: service_started
    networks:
      TMS-network:
        aliases:
          - frontend-network

networks:
  TMS-network:
    name: TMS-network
    driver: bridge

volumes:
  tms_mysql_data:
  ums_mysql_data:






