services:
  tms:
    image: tms:latest
    build:
      dockerfile: back-end/task-management-service/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/tms
  ums:
    image: ums:latest
    build:
      dockerfile: back-end/users-management-service/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/home/ums
