version: "3.9"

services:
  # database container for backend
  morshed_db:
    image: mysql:8.0
    restart: always
    container_name: morshed_db
    ports:
      - "3307:3306"
    expose:
      - 3307
    volumes:
      - morshed_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_ROOT_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - ../backend/.env

  # authentication service container
  morshed-app:
    image: python-service:3.11-bullseye
    build:
      context: ../backend/
      dockerfile: Dockerfile
    container_name: morshed-app
    depends_on:
      - morshed_db
    volumes:
      - ../backend/:/app/backend
    ports:
      - "8000:8000"
    command: ["gunicorn", "configs.wsgi:application",  "--bind", "0.0.0.0:8000 "]
    environment:
      PYTHONPATH: /app/backend/users_management_service
      DB_HOST: morshed_db
    networks:
      - morshed-network

networks:
  morshed-network:
    driver: bridge

volumes:
  morshed_db_data:






