version: "3.9"

services:
  pycharm-interpreter: # container for interpreter IDE
    image: python-pycharm:latest
    build:
      dockerfile: Dockerfile

  # task management service container
  tms:
    image: tms:latest
    build:
      dockerfile: task-management-service/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./task-management-service/:/home/task-management-service
    command: "uvicorn main:app --host 0.0.0.0 --reload"
    depends_on:
     - db_tms
    networks:
      tms-network:
        aliases:
          - tms

  # users management service container
  ums:
    image: ums:latest
    build:
      dockerfile: users-management-service/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./users-management-service/:/home/users-management-service
    command: "python manage.py runserver"
    depends_on:
      - db_ums
    networks:
      tms-network:
        aliases:
          - ums

  # database container for users management service
  db_ums:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db_ums
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root_123
      MYSQL_DATABASE: umsdb
      MYSQL_ROOT_HOST: '%'
    networks:
      tms-network:
        aliases:
          - db_ums

  # database container for task management service
  db_tms:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db_tms
    ports:
      - "3307:3306"
    expose:
      - 3307
    environment:
      MYSQL_ROOT_PASSWORD: root_123
      MYSQL_DATABASE: tmsdb
      MYSQL_ROOT_HOST: '%'
    networks:
      tms-network:
        aliases:
          - db_tms

networks:
  tms-network:
    name: tms-network
    driver: bridge


