name: Deploy to GCP

on:
  push:
    branches:
      - develop-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker images
      run: |
        docker-compose -f ./morshed_devops/docker-compose-front-end.yml build

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: SSH into instance and change permissions
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.INSTANCE_IP }}
        username: ${{ secrets.INSTANCE_USERNAME }}
        key: ${{ secrets.INSTANCE_SSH_KEY }}
        script: |
          sudo mkdir -p /app
          sudo chown -R $USER:$USER /app
          sudo chmod -R 755 /app

    - name: Copy Docker Compose file to instance
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.INSTANCE_IP }}
        username: ${{ secrets.INSTANCE_USERNAME }}
        key: ${{ secrets.INSTANCE_SSH_KEY }}
        source: "morshed_devops/docker-compose-front-end.yml, frontend/Dockerfile"
        target: "/app/frontend"
        strip_components: 1

    - name: SSH into instance and install Docker Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.INSTANCE_IP }}
        username: ${{ secrets.INSTANCE_USERNAME }}
        key: ${{ secrets.INSTANCE_SSH_KEY }}
        script: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER
          newgrp docker

    - name: SSH into instance and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.INSTANCE_IP }}
        username: ${{ secrets.INSTANCE_USERNAME }}
        key: ${{ secrets.INSTANCE_SSH_KEY }}
        script: |
          cd /app/frontend
          docker-compose -f docker-compose-front-end.yml down
          docker-compose -f docker-compose-front-end.yml pull
          docker-compose -f docker-compose-front-end.yml up -d
