name: Configure Python Backend Secrets
run-name: Pull request triggered by ${{ github.actor }}

on:
  push:
    branches:
      - "develop"
  pull_request:
    types:
      - opened

jobs:
  python-configure-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: MakeEnv file
        uses: SpicyPizza/create-envfile@v2.0.2
        with:
          envkey_DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          envkey_DJANGO_DATABASE_NAME: ${{ secrets.DJANGO_DATABASE_NAME }}
          envkey_DJANGO_DATABASE_USER: ${{ secrets.DJANGO_DATABASE_USER }}
          envkey_DJANGO_DATABASE_PASSWORD: ${{ secrets.DJANGO_DATABASE_PASSWORD }}
          file_name: .env

          
